### ISSUE TITLE
Add to npm?

### ISSUE THREAD

**Issue by bcomnes** [csstools/sanitize.css#1]
npm is a great way to package and distribute css now!  You can preprocess with grunt or other build tools right out of `node_modules`, and even better, @import right out of node_moduels using [things like browserify](https://gist.github.com/substack/68f8d502be42d5cd4942#css)

Would you be interested in adding this to npm?
- [x] Do we need to change the main file to /gulpfile.js or /dist/sanitize.css or /sanitize.scss?
- [x] How to handle scss vs css?

**Comment by bcomnes** [comment]
Great! https://www.npmjs.com/package/sanitize.css

I'll try to optimize the package.json for some of the standard browserify transforms.

**Comment by jonathantneal** [comment]
Thanks a ton, @bcomnes!

**Comment by jonathantneal** [comment]
@bcomnes, @pascalduez submitted a [change](https://github.com/jonathantneal/sanitize.css/commit/5ff28b7e8a34755c6644029ae083e01fbd4a2294) that addresses the main file. Does this resolve both sub-issues?

**Comment by pascalduez** [comment]
There are several modules using a `style` key in `package.json` so maybe worst adding it too ?
[npm-css](https://www.npmjs.com/package/npm-css)
[parcelify](https://www.npmjs.com/package/parcelify)
[...]

**Comment by bcomnes** [comment]
Parcelify is confusing me (It looks like it bundles css based on what you require in your main JS file... what do you do if there is no exportable js to include in your main field!?  Opened an issue here: https://github.com/rotundasoftware/parcelify/issues/28 ).  I'm mainly interested in consuming via npm-css though.  Sending the changes that make this possible right now.
