### ISSUE TITLE
Remove the outline only when hovering over links

### ISSUE THREAD

**Issue by tomasz1986** [csstools/sanitize.css#106]
The rule 

```
/**
 * Remove the outline when hovering in all browsers (opinionated.
 */

:hover {
    outline-width: 0;
} 
```

should be changed to

```
/**
 * Remove the outline when hovering in all browsers (opinionated).
 */

:link:hover {
    outline-width: 0;
} 
```

At the moment it is applied to all elements on hover, not only to links. The right bracket after `opinionated` is missing too.

**Comment by jonathantneal** [comment]
@tomasz1986, good point. I could qualify this with `a`, similar to [what I did in normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css#L97-L105).

Unfortunately, `:link` does not behave as you would expect.

> - The `:link` pseudo-class applies to links that have not yet been visited.
> - The `:visited` pseudo-class applies once the link has been visited by the user.
> 
> — https://drafts.csswg.org/selectors/#link

**Comment by tomasz1986** [comment]
The reality is different though. The browsers apply `:link` styles to all links.

I would do

```
:link:hover,
:visited:hover {
    outline-width: 0;
}
```

because while all `:link` (or `:visited`) are `a`, not all `a` are `:link`.

**Comment by jonathantneal** [comment]
True. Thanks for bringing this issue to my attention. `<a>` is rarely used as a pure anchor, nor would this change realistically affect that usage, so sanitize.css should limit selector weight whenever possible. I’ll make this change.

**Comment by jonathantneal** [comment]
Updated in [v4.1.0](https://github.com/jonathantneal/sanitize.css/commit/bf0fab34fef3ff2585b6332cdb91c4e1c8876103)

**Comment by tomasz1986** [comment]
Thank you for including the change. Just in case you decide to make it more specific, at the moment I would recommend

```
a:link:hover,
a:visited:hover {
    outline-width: 0;
}
```

I have been playing around with CSS profiler lately and found out that the browser treats things like `:link` as `*:link` and applies it to all elements, despite the fact that only anchors can use this pseudo-class. Thus, for performance reasons it is better to always write `a:link`, `a:visited`, etc.
