### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by vinkla** [csstools/sanitize.css#109]
In version 4 both the SASS and SCSS files seems to be gone? Is there a reason behind it? Is there another repository we can use instead?

**Comment by chrisvanpatten** [comment]
For those who encounter this in the future, libsass now allows you to [import/include raw CSS files by just omitting the .css extension](https://github.com/sass/libsass/pull/754), as you would any .sass or .scss file. This should supersede the need for dedicated Sass-compatible files.

(Not sure if this change tracked to the Ruby implementation of Sass.)

(Including the .css extension will render `@import url(path/to/file.css);`, as in previous versions.)

**Comment by vinkla** [comment]
@chrisvanpatten didn't know that. This has been a big flaw in earlier versions of SASS. Thanks for sharing.

**Comment by chrisvanpatten** [comment]
Happy to help! It's a great little fix that wasn't well advertised. Hope it helps others.

**Comment by pavelhamrik** [comment]
This 'feature' is now being deprecated. What is the current best practice? Creating that importer just for this? Relying on Webpack and such?

```
DEPRECATION WARNING [line and file ref omitted]:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
```
