### ISSUE TITLE
Global 100% width

### ISSUE THREAD

**Issue by AntonTrollback** [csstools/sanitize.css#117]
Just an idea. 

```
* {
  width: 100%
}
```

It completely ruins the Github page I played with but there CSS contains `width: 100%` 150 times.

Fixes a lot:

```
svg, img {
  width: auto;
}
```

Not sure if it can be done without killing `width="x"` attributes (`*:not([width])` alters specificity).

Might be annoying having to set `width: auto` to inline-block elements. Not sure if it's a deal breaker.

I don't know. I mostly dislike cases where `width: 100%` is needed but hard to remember. Like say, working with truncating text and breaking words.

**Comment by jonathantneal** [comment]
While that’s an interesting way to save a few bytes, it’s not a useful default. One could just as well make everything display:flex or display:block, which has been suggested before.
