### ISSUE TITLE
Make the use of the cellspacing attribute on <table> easier

### ISSUE THREAD

**Issue by 7studio** [csstools/sanitize.css#120]
Hi,

I know that it was already discussed in Normalize.css (and now removed):

- [`table`'s minor improvement #354](https://github.com/necolas/normalize.css/issues/354)
- [Remove border-spacing: 0 in table element #165](https://github.com/necolas/normalize.css/issues/165)

but I encountered some problems with the declaration `border-spacing: 0` on HTML `<table>` elements when I used Sanitize.css recently.

In my case, I used a Wysiwyg editor (TinyMCE or CKEditor) and sadly this tool uses the HTML `cellspacing` attribute to specify the distance between the borders of adjacent table cells.
However, as the CSS declaration is more important than the HTML attribute, you can't use this feature (without hacking the code and/or Sanitize.css) :pensive:

As the `border-spacing` CSS property applies only when `border-collapse` is separate, it will be safer to remove this declaration :wink:
If the Sanitize's goal is just to remove additional border spacing, the CSS declaration `border-collapse: collapse` is enough.

I hope you will also consider all arguments into the Normalize.css issues.

Thank you for your time.

**Comment by jonathantneal** [comment]
Excellent review. Thank you. Resolved in https://github.com/jonathantneal/sanitize.css/commit/3c44316082957ec1b216b76149b2d4bcd0dd8e14
