### ISSUE TITLE
(Suggestion) word-break: break-all

### ISSUE THREAD

**Issue by fregante** [csstools/sanitize.css#121]
`word-break: break-all` and `overflow-wrap: break-word` seem to only be suggested across internet as a solution to non-wrapping long words/URLs, which easily break flexible layouts.

... but I couldn't find any drawbacks on having this as default across the site. It doesn't sound like it would break anything (except, well, _words_) so what do you think about adding it to `sanitize.css` on `html`?

**Comment by bfred-it** [comment]
Well, no. Apparently it can also break text in places you don't want it to 😕

**Comment by bfred-it** [comment]
Nevermind, the break was happening exactly where it was supposed to happen and I haven't had any issues since :D

**Comment by DJTB** [comment]
FYI `word-break` does not have a `break-word` value it has `break-all`, only `word-wrap`/`overflow-wrap` has `break-word`.

`Word-break` with `break-all` is probably the better option overall.

**Comment by fregante** [comment]
Corrected, thanks

**Comment by jonathantneal** [comment]
Great! Let’s do some polling! https://twitter.com/jon_neal/status/851778801377955842

**Comment by jonathantneal** [comment]
@bfred-it, still interested in this?

**Comment by fregante** [comment]
Yep!

**Comment by jonathantneal** [comment]
Going to add this as well.

**Comment by tomasz1986** [comment]
Please test this with tables because I do remember having issues related to this setting. I do not remember the details now though but I ultimately ended up reverting to the default browser behaviour.

**Comment by fregante** [comment]
Table expand to fit the content, I can see how it would change its behavior. However, how does the table behave without it? It will overflow its set width, right?

**Comment by jonathantneal** [comment]
I will add this.

**Comment by jonathantneal** [comment]
Added in v6.0.0! 🎉

**Comment by fregante** [comment]
I’m hopeful for a future where this doesn’t happen 🙂 


![a955ae5c-2629-4bae-9d24-a5e310f5d9f0](https://user-images.githubusercontent.com/1402241/41855933-26a19254-7894-11e8-8faf-821cb2c41d69.png)

**Comment by jonathantneal** [comment]
Yes, this change would have fixed that 😛 

By the way, the change wasn’t ultimately `break-all`, it was `break-word`.

**Comment by fregante** [comment]
Yes perhaps `break-word` is a less aggressive default

**Comment by notiv-nt** [comment]
@jonathantneal @bfred-it take a look please.

The issue is closed but still relevant.

## What about:

```
word-break: break-all; /* Firefox */
word-break: break-word; /* Chrome/Safari/Edge/IE9+ */
```

## Or better solution:

Looks the same in all browsers.

```
word-break: break-word;
word-wrap: break-word;
```

It works https://jsbin.com/zinetit/edit?output

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Browser_compatibility
https://github.com/csstools/sanitize.css/blob/master/sanitize.css#L60

### Edge

![image](https://user-images.githubusercontent.com/10743009/50692663-b6f7ed00-1045-11e9-87d3-4e293ec65fbf.png)

### Chrome/Safari/FF/IE9 (-grid / -flex)

![image](https://user-images.githubusercontent.com/10743009/50692700-caa35380-1045-11e9-936f-9b13d60e36d0.png)
