### ISSUE TITLE
Lobotomized owl

### ISSUE THREAD

**Issue by sundarj** [csstools/sanitize.css#124]
See http://alistapart.com/article/axiomatic-css-and-lobotomized-owls

**Comment by jonathantneal** [comment]
I don’t understand what this has to do with this project, or why you have altered the link you are sharing..

**Comment by sundarj** [comment]
I figured `* + * { margin-top: 1.5em }` is a nice default set of margins (that can anyway be easily overwritten) - as for the link edit, I figured it's safer to link to a Wayback Machine'd link (it's SO best practice at least).

Thanks for your time :)
