### ISSUE TITLE
How to use this after installing with npm?

### ISSUE THREAD

**Issue by tashburn** [csstools/sanitize.css#127]
Once installed via `npm install --save sanitize.css`, what's the intended way for this to be used? I'd love some usage guidance to be included in the README.

(In my case, in a node.js / webpack / react project)

**Comment by sylvaindethier** [comment]
Configure webpack so it can load CSS files (style-loader, css-loader).
Then in a JS file: `import 'sanitize.css/sanitize.css'`

**Comment by jonathantneal** [comment]
Thank you, @sylvaindethier .

**Comment by mario-d-s** [comment]
@jonathantneal could you please add this to the README?

**Comment by jonathantneal** [comment]
I’m unsure of what those directions would look like for Webpack. If you could write out a minimal webpack configuration for this, followed by the `@import` example in CSS, either in a comment here or as a PR, then I would be happy to add it.

Here’s an example of the webpack configuration for postcss-normalize: https://github.com/csstools/postcss-normalize/blob/master/INSTALL.md#webpack

**Comment by mario-d-s** [comment]
@jonathantneal you are right, it really depends on the build system used and even then it's not really necessary as you can use plain `@import` in CSS (or preprocessors) as well.

I would _like_ to make up a PR if you want but I'm really just in a learning stage with all this frontend stuff. I doubt I could deliver quality guidance on it myself.

**Comment by jonathantneal** [comment]
@mario-d-s, I think you’ve already started formulating a decent resolution. The act of editing the markdown file and submitting a PR will probably get it enough of the way there that I could help carry it all the way through. Anyway, I’d love to work with you on this, if you end up making that PR.

**Comment by mario-d-s** [comment]
@jonathantneal sorry for not getting back to you sooner but thank you for your encouragement. I'll have a look at it later today!
