### ISSUE TITLE
Table text-align inheritance

### ISSUE THREAD

**Issue by dbox** [csstools/sanitize.css#128]
@jonathantneal thoughts on this?

```css
table th, table td {
   text-align: inherit;
} 
```

**Comment by jonathantneal** [comment]
Yea, I actually really like that. Do we have examples of this on the web?

**Comment by jonathantneal** [comment]
Considering this something to add.

**Comment by dbox** [comment]
I feel like I needed this at one point, but then went back to test it again, and it was doing it out of the box. I need to re-test

**Comment by jonathantneal** [comment]
@dbox, so was this _not_ an issue? If so, may we close it?

**Comment by dbox** [comment]
Not an issue! closing
