### ISSUE TITLE
(Suggestion) setting base font-size on html

### ISSUE THREAD

**Issue by code4cake** [csstools/sanitize.css#130]
Setting a default value to `font-size` so it can be more scalable with`rem`?

```
html {
  font-size: 62.5%;
}
```

I could add it as a PR if you guys think is valuable

**Comment by jonathantneal** [comment]
Two thoughts / responses:

1. 12pt aka 16px is a comfortable default, and one of the better default UA choices on the web.
2. This is easily defined once in your own stylesheet. The sanitize.css stack goes: normalize.css for browser bugs, sanitize.css for preferred defaults that do not match UA defaults.

**Comment by code4cake** [comment]
@jonathantneal thanks for the clarification and for the reply.
