### ISSUE TITLE
Is background-color: transparent on form elements an issue?

### ISSUE THREAD

**Issue by simevidas** [csstools/sanitize.css#133]
When form elements are not styled by the web page, the browsers render them natively, i.e. they look like native controls on the user’s platform.

I’ve noticed that adding sanitize.css removes those native styles from my form elements. They appear unstyled and have ugly borders. If I understand correctly, this means that using sanitize.css **requires** the web page to style the form elements itself. 

![foo](https://cloud.githubusercontent.com/assets/716405/25644505/f4388520-2fa6-11e7-8ea8-0db02b838bf6.png)

I’m wondering if it’s possible to use sanitize.css and still have form controls rendered by the browser as native controls. For now, I’ll use [my fork](https://github.com/simevidas/sanitize.css/commit/1e5c2b27f801f35c46fb2d5191decffb0426c05e) which doesn’t include the problematic line. It’s an ok hotfix, but I’m curious if there’s a better solution.

**Comment by HiroAgustin** [comment]
From the [README](https://github.com/jonathantneal/sanitize.css#form-controls-should-be-easily-style-able):

> Form controls should be easily style-able

I believe that's the reasoning for removing the background color. As you said, the intention of this particular css “reset” is to provide a base experience for developers to style the elements.

> …normalize.css styles adhere to css specifications. sanitize.css styles adhere to common developer expectations and preferences…

Maybe normalize.css is better suited for what you are trying to achieve.

**Comment by simevidas** [comment]
@HiroAgustin I’m not sure I understand. How does sanitize.css adding `background-color: transparent` make form controls more easily styleable? If the developer wants to style the backgrounds, borders, etc. of form controls, they can do that with or without this particular line in sanitize.css.

It seems to me that `background-color: transparent` in sanitize.css serves no other purpose other than disabling the native appearance of form controls in browsers. Please correct me if I’m wrong. Note that the native appearance is also disabled as soon as the developer starts styling the form controls themselves.

**Comment by HiroAgustin** [comment]
The only example I can think of is when trying to style a button to look like a link.

**Comment by simevidas** [comment]
@HiroAgustin I’m not sure how that is related. If a web developer wants to make a button look like a link, they can do that easily. Sanitize does not interfere with that. 
 
What Sanitize does is, it disables the native styling of form controls (by setting `background-color: transparent`). I’m trying to understand what the purpose of that property is. Maybe some sites that use Sanitize, rely on form controls being transparent. But then, if they already style form controls, can’t they just add that one property themselves. That way, folks like me who want to use native styling, won’t have to fork Sanitize just to remove that one line.

**Comment by jonathantneal** [comment]
@simevidas, I agree with you. Want to file a PR? Otherwise, I’ll just need to remember.

**Comment by simevidas** [comment]
I can do it, no problem!

**Comment by simevidas** [comment]
Just for the record, I’ve noticed the following rule in sanitize.css

```css
*,
::before,
::after {
  background-repeat: no-repeat; /* 1 */
  box-sizing: border-box; /* 2 */
}
```

causes ugly buttons in the current version of Safari on desktop.

I’ve fixed this issue on my end by resetting the `background-repeat` value on my button

```css
[type="submit"] {
  background-repeat: initial;
}
```

which luckily works, so it is not absolutely necessary to deal with this issue in sanitize.css itself.
