### ISSUE TITLE
Consider adding !important to the [hidden] style rule

### ISSUE THREAD

**Issue by simevidas** [csstools/sanitize.css#134]
Monica Dinculescu has [pointed out](https://mobile.twitter.com/notwaldorf/status/867803697325129728), that the default styles for `[hidden]` can be easily overridden, and that it’s probably a good idea to add `!important`:

```css
[hidden] { display: none !important }
```

This change should not break any sites (since that would mean that they were displaying `hidden` content), but it would protect sites from accidentally displaying `hidden` content.

**Comment by jonathantneal** [comment]
@simevidas, interesting proposal. I’m not sure adding `!important` will help more than it hurts. For instance, some people may still rely on the visually hidden technique of `[hidden][aria-hidden="false"]`, which would require unsetting the important from `[hidden]`.

Still, this is an interesting proposal. Do we have any evidence of `[hidden]` not being hidden on living sites, due to developers forgetting its unusual low specificity?

**Comment by simevidas** [comment]
Makes sense. I’ll report back if I encounter a case where the `[hidden]`  rule was accidentally overridden.

**Comment by rstacruz** [comment]
This makes a lot of sense. Consider this example:

```css
ul.nav > li { display: inline; }
```

with:

```html
<ul class='nav'>
  <li hidden></li>
</ul>
```

The `display: inline` declaration would override `[hidden]`.

**Comment by jonathantneal** [comment]
It would without sanitize, as well. This would hijack the aria-hidden false scenario.

**Comment by simevidas** [comment]
@jonathantneal I guess, I didn’t understand this at the time, but now I noticed that your example, `[hidden][aria-hidden="false"]`, violates the HTML spec:

> It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked `hidden`, it is hidden from all presentations, including, for instance, screen readers.

https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

It is not correct to use `hidden` in combination with `aria-hidden="false"` to visually hide content. There is unfortunately no standard way to do this, and a custom CSS “visually hidden” class is needed.

Setting `hidden` means “hide from all presentations,” so applying `display: none !important` should not   cause issues on pages that use `hidden` correctly.
