### ISSUE TITLE
change to a license convenient for adoption by enterprises

### ISSUE THREAD

**Issue by ilatypov** [csstools/sanitize.css#136]
The CC0 license can “weaken patent infringement defenses available to users of software released under CC0” https://opensource.org/faq#cc-zero

The affirmers may not have “all the necessary rights to grant permission to use the CC0’d work” https://wiki.creativecommons.org/wiki/CC0_FAQ#How_can_I_be_sure_that_I_have_all_the_rights_I_need_to_use_the_work.3F

I am worried this may prevent from adopting this npm module by my employer.  OSI suggests MIT or a few other licenses that seem to fit the "legal climate".

**Comment by rstacruz** [comment]
Since CC0 is public domain, couldn't you re-release your own version of sanitize.css under MIT?

**Comment by jonathantneal** [comment]
I have a number of modules out there as CC0. GPL explicitly states compatibility. http://www.gnu.org/licenses/license-list.html#CC0

Have not read of this ever being an issue. Closing.
