### ISSUE TITLE
Hand cursor on buttons

### ISSUE THREAD

**Issue by rstacruz** [csstools/sanitize.css#138]
Would you consider this change?

```css
button, input[type="button"], input[type="submit"] {
  cursor: pointer;
}
```

**Comment by rstacruz** [comment]
@nicolasparada, care to chime in on why not?

**Comment by nicolasparada** [comment]
https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by m-e-h** [comment]
https://github.com/twbs/bootstrap/pull/21812

**Comment by sholladay** [comment]
Conceptually, I like the "hand cursor is only for non-obvious elements" mantra. And it is consistent with what operating systems do, which makes it easier to use sanitize.css as-is in a desktop app (e.g. via Electron).

That said, look at GitHub, it is using the hand cursor for _everything_ and I like it a lot in practice. 
¯\\\_(ツ)_/¯

**Comment by jonathantneal** [comment]
Going with @nicolasparada’s advice.
