### ISSUE TITLE
Normalize input colours

### ISSUE THREAD

**Issue by clarfonthey** [csstools/sanitize.css#140]
Essentially, something along the lines of:

```
input, select, textarea {
    background-color: white;
    color: black;
}
```

This was marked as wontfix by the original `normalize.css` project but it seems reasonable to add here.

**Comment by dashed** [comment]
Do certain browsers change the font color?

**Comment by clarfonthey** [comment]
@dashed not necessarily the browsers themselves, but oftentimes the operating system's default theme is used to style forms. And, oftentimes, websites only set the colour or the background when not every system defaults to black font, white background.

**Comment by jonathantneal** [comment]
I’d rather another library handle inputs. They are, by design, OS specific. The only normalizations I would accept would be those that used (deprecated) system colors. And I would accept them if they supported hypothetical OS dark modes.
