### ISSUE TITLE
Problem with "cursor root-cursor"

### ISSUE THREAD

**Issue by scoutrul** [csstools/sanitize.css#141]
Hello! Thank you for this plugin, I very like it!
I have a little problem with this option:
> :root
    box-sizing root-box-sizing
    cursor root-cursor
      font root-font-size/root-line-height root-font-family <= I have delete this
      text-rendering root-text-rendering;

Plugin named 'Typography' can't do responsive font because of this option.
How much this option important and why, tell me please.

**Comment by jonathantneal** [comment]
I think you’ll need to explain how a mouse cursor affects typography?

**Comment by scoutrul** [comment]
I meant line with font props. And yes, this font reset give problem to typography plugin.

**Comment by jonathantneal** [comment]
I’m sorry. The `cursor: default` doesn’t appear to be a problem, so I will not be changing this.
