### ISSUE TITLE
Different content on the same version (master branch vs npm)

### ISSUE THREAD

**Issue by danieleleoni** [csstools/sanitize.css#143]
Hi guys,

following this issue
https://github.com/jonathantneal/sanitize.css/issues/133
I noticed that sanitize.css marked as 5.0.0 is not the same I get from npm, marked as 5.0.0 as well

Particularly refer to 
```
button,
input,
select,
textarea {
        background-color: transparent;
	color: inherit;
	font-size: inherit;
	line-height: inherit;
}

```

Where
`background-color: transparent;`
was found on npm and not on your master branch.

Is there anything I'm doing wrong?

**Comment by danieleleoni** [comment]
UPDATE:
even installing with `yarn add https://github.com/jonathantneal/sanitize.css#^5.0.0` I received content I didn't expect.

`yarn add https://github.com/jonathantneal/sanitize.css#master` indeed gets what I want.

**Comment by cloud-walker** [comment]
News on this?

**Comment by jonathantneal** [comment]
If this is still an issue, I will correct this in the next release.

**Comment by ArmanNisch** [comment]
This seems to be an issue again. I have tried the following install options:
1) yarn add sanitize.css
2) yarn add sanitize.css@^8.0.0

In both cases the file that I get is **sanitize.css v7.0.3** and not v^8.
