### ISSUE TITLE
H1 correction vs font margins

### ISSUE THREAD

**Issue by ludasmokva** [csstools/sanitize.css#144]
I am an amateur when it comes to web design, so please forgive me if these are 'duh' questions. :)
After blindly utilizing various resets, I've come to realize that in many cases my efforts are being duplicated.
I want to 'reset' or 'normalize' only the functions I would expect to act in a different way and therefore would not normally 'adjust'. 
Example: I expect all margins and/or padding to be at 0, so would not normally expect to have to identify that in my CSS unless I want a margin/padding other than 0.  Similarly, I would expect all my H1 to be xREM, and would not expect that to change unless I specify it. 

To that end, I am somewhat confused with the following:
1. All headings, including H1 should be styled according to the design; and font-size is a basic style. Why would I correct the H1 appearance only to change it again? Or is there something I am missing? 

2. Margins and padding around headings, p, blockquotes, ul, ol, images (and who knows what else) should be at 0 in my opinion. That is an expectation on my part and as such, would never think of adding it to my styling unless I am trying adjust the layout - and I would usually adjust the container. I often find myself wondering why text is appearing different that I calculated... Is there a specific reason you have chosen not to  address this? 

3. is there a particular reason you do not address font-smoothing? 

Again, I apologize if my questions are simplistic. I liked your approach to resets and am incorporating it now, but found myself wanting to skip certain sections and add other things. And then I thought...  hmmm... maybe there is a good reason you took this approach, so I thought I'd ask.

**Comment by jonathantneal** [comment]
1. sanitize.css doesn’t work against browser defaults, and it includes parts of normalize.css that fix discrepancies between browsers. Defining `h1` sizing corrects one such discrepancy. The note indicates the issue, which has to do with when the element is found within an `article`.

2. If you want to undo browser defaults, a reset would be better. this isn’t a reset. it’s more like normalize but with “more sensible” defaults based on common developer practice.

3. No. Font smoothing is not something I’ve read needs correcting widely.
