### ISSUE TITLE
In Addition To, or Instead Of?

### ISSUE THREAD

**Issue by strider72** [csstools/sanitize.css#145]
You should add a note to the Readme: is this supposed to be used _in addition to_ normalize.css, or _instead of_ normalize.css?

Edit to add: I figured it out, but it wasn't immediately obvious, and should be ;-)

**Comment by conradkleinespel** [comment]
@strider72 Which is it ? Looks like it could be whatever you want it to be. Some styles are in both. But some styles are in only one of them (both ways, ie the styles for the `html` tag)

**Comment by strider72** [comment]
Sanitize (theoretically) has everything from normalize, PLUS a number of "opinionated" changes.  You only need one or the other; sanitize is a superset of normalize.

**Comment by jonathantneal** [comment]
Yes. This is a non-issue, though I appreciate raising issues with the language of the README.

I may need to change the wording entirely, since normalize.css has gone into development silo.

**Comment by sethlivingston** [comment]
I had a hard time finding this.
