### ISSUE TITLE
Suggestion: Datalist background color

### ISSUE THREAD

**Issue by strider72** [csstools/sanitize.css#147]
In IE and Edge, a Datalist dropdown defaults to the background color of the containing element.  Firefox and Chrome use the Windows window background color (usually white, but changeable is system settings).

For (reasonable) standardization, we should explicitly set them to black and white:
```
input[list] {
	color:black;
	background-color:white;
}
```

This will not change Firefox or Chrome if Windows has a different setting for window background color, but it will tell IE and Edge to use black and white, which will *usually* match FF/Chrome.  Without it, there can be significant variance between browsers, and even from one datalist to another.

**Comment by strider72** [comment]
Related: #140

**Comment by jonathantneal** [comment]
Closing for the same reason as #140
