### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by cloud-walker** [csstools/sanitize.css#149]

**Comment by jonathantneal** [comment]
Nope. 😄

**Comment by cloud-walker** [comment]
So whats the reason for the inactivity? Can I help?

**Comment by jonathantneal** [comment]
Absolutely. Yes, I don’t see any PRs, so maybe just commenting on whether issues can be closed or what the PR should look like — that would help.

**Comment by cloud-walker** [comment]
I've created my first PR, can we publish a new sanitize version after this? Ref. #143
