### ISSUE TITLE
Revive search-cancel-button

### ISSUE THREAD

**Issue by wulfsberg** [csstools/sanitize.css#152]
Feature request: Remove the 
```
[type=search]::-webkit-search-cancel-button {
    -webkit-appearance: none
}
```
per https://github.com/necolas/normalize.css/issues/685#issuecomment-305393313

**Comment by jonathantneal** [comment]
I’d like not to remove features. Only to normalize features or set reasonable, universal defaults.

**Comment by wulfsberg** [comment]
Currently, sanitize.css specifically _removes_ the "clear search field" button which almost all browsers have.
It seems to be a fairly heavy price to "normalize" to lowest common denominator in this case.

**Comment by jonathantneal** [comment]
You are right. I must not have brought over certain updates to normalize during my second wind on that project. I will specifically remove these unnecessary “lower common denominator” changes. normalize and sanitize should always fall forward. Well, no guarantees with normalize anymore.
