### ISSUE TITLE
Nav lists

### ISSUE THREAD

**Issue by equinusocio** [csstools/sanitize.css#155]
Hi @jonathantneal, thank you for this work. It's now time to move on and leave back old utilities like normalize (that support very old browsers) and resets.

I really like your clean and surgical approach but I have a thought about the `nav ol, nav ul` code. The `nav` element specification says ([EXAMPLE 11](http://w3c.github.io/html/sections.html#the-nav-element)) that it doesn't have to contain a list element and provide an example with paragraphs inside.

So i think that users can choose to use (or not) a list inside a nav, then providing a reset code for this situation can be useles for those who don't use any list inside a nav (like me), resulting in unused code. 

What do you think about removing this assumption from the code?

**Comment by jonathantneal** [comment]
Yes, it may not always be used, but it would be expected in many scenarios, and it is officially recommended:

> In cases where the content of a nav element represents a list of items, use list markup to aid understanding and navigation.
> — https://www.w3.org/TR/html/sections.html#the-nav-element

Does this seem reasonable?

**Comment by equinusocio** [comment]
Right now the css does not provide a css fix for the cross browser consistency, it provide a custom and personal look and feel by just removing a standard rapresentation (list style) only inside the nav element. I don’t think this is related to browesers inconsistency at all..

The spec tell that you can put a list inside a nav to help navigation, does not tell that you should always remov the dots..these two thing are not related. 

The fact that you already closed this issue tell me and to other people that you don’t want to talk about this project or hear other people’s thoughts 😔

**Comment by jonathantneal** [comment]
Please forgive my confusion or any hint of aggression, but I never said anything about _inconsistencies_, so you might be reading more into what I’m saying than I mean to express.

normalize.css is the library that deals with exclusively _normalizing_ things. This library also includes common developer preferences, like `box-sizing: border-box`, etc.

Your opinion on whether or not to use lists is totally allowed and shared by others. In fact, many years ago, we all kind of hashed out our thoughts https://css-tricks.com/wrapup-of-navigation-in-lists/

In the end, I think requests like this are a good reason to make a PostCSS version of this library, where one can remove certain rules by options at build time. 😄

**Comment by equinusocio** [comment]
> sanitize.css is a CSS library that provides consistent, cross-browser default styling of HTML elements alongside useful defaults.

The point is.. what can be defined useful? :)

The issue not to put or not a list inside a nav, but removing their dots by default, for each list inside all nav.. Just this :) btw, i agree that a postcss plugin can be really awesome.
