### ISSUE TITLE
SVG rendering inconsitency?

### ISSUE THREAD

**Issue by ludasmokva** [csstools/sanitize.css#159]
Not sure if this would apply, so apologies in advance if this is beyond the scope of sanitize. 
I was creating a fiddle and noticed that my SVG rendered differently in FF vs Chrome and Opera (even Vivaldi). In Firefox, the SVG showed properly (svg icon + text next to it).
In Chrome, Opera and Vivaldi, the svg and the text showed up on separate lines, with the svg taking up the whole line (like a block item) and centering. 
Here is the [link](https://jsfiddle.net/Smokva123/0j6dou1z/) View it in the different browsers.

I am still in the process of figuring out what is causing the issue (svg, input, label...), so I am afraid I can't help you there. Perhaps you will see something I have not yet spotted.  I can only say that I think it has more to do with SVG, only because when I preview my website page, I am having problems with some other SVG icons. In one case, the SVG icon again appears centered even with a 'fixed' position applied (top 0 and left 0). And the other issue is with a svg hamburger icon that is simply not allowing itself to be 'clicked' and therefore does not show the menu.  Again, those could be completely separate issues. Other SVGs with links work fine.  Everything seems to render properly (how you would expect based on the code) in Firefox. The code used is fairly established, so I have not seen any usability issues. So that's why I figured it may be a browser rendering inconsistency. 

If I figure out why this is happening, I will add to this post. But I figured it may be of interest. 

Edit: Updated link

**Comment by jonathantneal** [comment]
This is outside the scope of sanitize, as it has more to do with how different browsers draw vectors. The best expert I know of to ask questions like this to is [Amelia Bellamy-Royds](https://twitter.com/AmeliasBrain).

**Comment by ludasmokva** [comment]
Thank you! 
However, I still bet that sooner or later it will be addressed in one way or another. ;)
Have a great day.
