### ISSUE TITLE
`vertical-align: inherit` makes `code` baseline weird

### ISSUE THREAD

**Issue by ungoldman** [csstools/sanitize.css#16]
https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss#L99

expecting:
![screen shot 2015-03-29 at 1 13 04 pm](https://cloud.githubusercontent.com/assets/427322/6887468/623fa5be-d615-11e4-998a-31c75dc18ea3.png)

seeing:
![screen shot 2015-03-29 at 1 12 49 pm](https://cloud.githubusercontent.com/assets/427322/6887467/623f1a68-d615-11e4-8c7c-39ef8c5aee8a.png)

Was looking for more-or-less parity with `normalize.css`, would you say this is how `code` elements are intended to be rendered by default with `sanitize.css`?

**Comment by jonathantneal** [comment]
This has been addressed. https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss#L154-L163

Thoughts?

**Comment by jonathantneal** [comment]
Yes, I too had this issue. Vertical alignment is now only specified on media elements. Does this change resolve the issue for you, too?

**Comment by ungoldman** [comment]
@jonathantneal I think so. Just part of https://github.com/jonathantneal/sanitize.css/commit/b65fc7c0f53627a0fc7ceca6c6251e8bfd97a333 and not released yet, right?

**Comment by ungoldman** [comment]
Woops, meant to point to https://github.com/jonathantneal/sanitize.css/commit/fbc33d011a8c5e67c71ced22b9d2762cb1ef9e69 (same commit message)

**Comment by jonathantneal** [comment]
This is now resolved in 2.0.0
