### ISSUE TITLE
Global background image properties

### ISSUE THREAD

**Issue by niksy** [csstools/sanitize.css#17]
What is your take on applying global properties such as `background-repeat:no-repeat;` or `background-position:0 0;`? It seems to me that basically the starting point for every background image setting and yet it almost always needs to be reset to these values.

**Comment by jonathantneal** [comment]
@niksy, I agree. Have you seen Chris Coyier’s post on the subject? https://css-tricks.com/things-it-might-be-funuseful-to-try-the-universal-selector-on/

**Comment by niksy** [comment]
@jonathantneal I knew that I saw it somewhere a while ago! :) I think this is one of those nuggets that really work on majority of projects, but only if you commit yourself to non-shorthand properties, which you would probably do anyway if you’re using `background-size` or one of the newer properties, either because you don’t know their order or you need to prefix them.

Do you know any edge case of using this?

**Comment by jonathantneal** [comment]
FYI, the default `background-position` appears to be [`0 0`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position). `background-repeat` will be in the next release.

**Comment by jonathantneal** [comment]
Annnnd done!
