### ISSUE TITLE
Custom text selection color causes text selection not to be visible in FireFox when in High-Contrast mode

### ISSUE THREAD

**Issue by robgeorge9** [csstools/sanitize.css#173]
When text is selected by the user, a background highlight is shown to indicate the range of text that is selected. For users of the FireFox browser on Windows machines running High-Contrast mode the text selection highlight is invisible when custom colors are used. For accessibility purposes, it is best practice to not overwrite text selection colors. 

Please consider removing the following. 
::-moz-selection
{ background-color:#b3d4fc; color:#000; text-shadow:none }

::selection
{ background-color:#b3d4fc; color:#000; text-shadow:none }

**Comment by jonathantneal** [comment]
Certainly, I’ll either need to test this to be certain or get a citation from you. Could you do that? This rule was added to improve accessibility, because text selections with text shadows are much harder to read.

**Comment by robgeorge9** [comment]
The problem with overwriting the selection colors comes when you are using Windows High Contrast mode without IE. IE will not allow the overwrite to work, as WHC mode overwrites the styles inline. The problem comes with non-native browsers as it is not able to enact on the overwriting of styles and thus can render out incorrectly.

**Comment by jonathantneal** [comment]
@robgeorge9, does Firefox support a high contrast mode media query? I could make this change wrapped in that media query.

**Comment by robgeorge9** [comment]
Since FF is not a native browser to the OS, Windows High Contrast mode is not supported to the full extent. Unfortunately, this is a limitation of the system built into the OS. Both FF and IE are both preferred browsers for PCs, so it's a bit unfortunate that it was overlooked in development, as they did create a media query for IE using WHC, just not FF.

**Comment by jonathantneal** [comment]
Would you be able to provide some screenshots? If so, I think we can make this change, despite the slight downgrade it means for other, aforementioned scenarios.

**Comment by jonathantneal** [comment]
I will be on vacation for a few weeks, but if you’re able to provide some screenshots, I’m still open to resolving this issue with you.

**Comment by robgeorge9** [comment]
Yes sorry, I'll be back in the office on Friday. I will send through screenshots then.

**Comment by robgeorge9** [comment]
Jonathan, 

Here are the screenshots you requested. I've supplied both how IE and Firefox treats text selection on our website along with Yahoo.  

Firefox
<img width="1475" alt="firefox_bbby_text_selection" src="https://user-images.githubusercontent.com/22483026/50528438-518f8380-0abc-11e9-9e98-1ecc5d38203c.png">
<img width="1491" alt="firefox_yahoo_text_selection" src="https://user-images.githubusercontent.com/22483026/50528439-518f8380-0abc-11e9-984c-e33cd1391fa6.png">

IE
<img width="1436" alt="ie_bbby_text_selection" src="https://user-images.githubusercontent.com/22483026/50528441-518f8380-0abc-11e9-8354-d283cbe33e44.png">
<img width="1451" alt="ie_yahoo_text_selection" src="https://user-images.githubusercontent.com/22483026/50528440-518f8380-0abc-11e9-9d89-0dacbd778a7d.png">

Let me know if you need anything else.

**Comment by jonathantneal** [comment]
Thank you for the feedback, and I apologize for the late response. Yes, I will remove this in the next major release.

**Comment by tigt** [comment]
Thank you for making this change to restore the correct selection colors to HCM users.

I’m curious, does:

```css
::-moz-selection {
  text-shadow: none;
}

::selection {
  text-shadow: none;
}
```

…have the same problem? Disabling `text-shadow` was a pretty good usability move, in my opinion.

**Comment by jonathantneal** [comment]
@tigt, good point, and thanks for bringing it up because I hadn’t considered that. @robgeorge9, any concerns with disabling text-shadow, which was originally done in the service of usability?

**Comment by tigt** [comment]
I can’t test HCM in Firefox due to my company’s draconian installation policy, but I can confirm that by default IE ignores `text-shadow` altogether in High-Contrast Mode, so barring weird side-effects, it should be safe to remove for everyone inside a selection.

**Comment by robgeorge9** [comment]
@jonathantneal @tigt - No issues with the text-shadow. Feel free to add that back.
