### ISSUE TITLE
small tag and default font size

### ISSUE THREAD

**Issue by cara-tm** [csstools/sanitize.css#174]
Google Chromium and Firefox latest versions declare a 80% font-size for the `small` tag within their default user stylesheets. So, maybe the best way is to use this instead:

    small {
        font-size: smaller
    }

to avoid a 80% reduced font changed by 80%.

See: https://github.com/csstools/sanitize.css/blob/master/sanitize.css#L190

**Comment by jonathantneal** [comment]
There isn’t consensus around the particular sizing of the `smaller` keyword, and it is implemented differently in Microsoft browsers. The [HTML Living Standard](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) section on presentational hints suggests using `smaller` for `<small>`, but the [CSS Fonts Level 3 Specification](https://drafts.csswg.org/css-fonts-3/#propdef-font-size) does not provide an opinion on what size that is.

In browsers, the following table describes the delta between what browsers do by default, what normalize/sanitize scripts do, and what `font-size: smaller` would do:

| Browser | `<small>` | `font-size: 80%` | `font-size: smaller` |
| --- | --- | --- | --- |
| Internet Explorer 9  | 83%    | 80% | 66.6~% |
| Internet Explorer 10 | 83%    | 80% | 66.6~% |
| Internet Explorer 11 | 83%    | 80% | 66.6~% |
| Microsoft Edge 18    | 83%    | 80% | 66.6~% |
| Chrome 70            | 83.3~% | 80% | 83.3~%  |
| Firefox 63           | 83.3~% | 80% | 83.3~%  |
| Safari 12            | 83.3~% | 80% | 83.3~%  |

Between Apple, Google, Microsoft, and Mozilla, 3 of 4 prefer a font-size of `83.3~%` over `83%`, and all of them prefer something closer to `83%` than `80%`.

Redefining the `font-size` for `<small>` to be either `calc(100% * 5 / 6)`, `calc(500% / 6)`, or `calc(250% / 3)`, works in all modern browsers.

To preserve compatibility with Internet Explorer 9-11, this number has to change to `calc(250 / 3%)`, but this will cause Internet Explorer and Edge to round the number to `83%`. Any combination of `calc()` that will give Edge `83.3~%` will give Internet Explorer 9-11 `12.5%` for some reason.

If we can figure out a way to give `83.3~%` to all browsers, I will gladly make this change here and in csstools-normalize and postcss-normalize.

**Comment by cara-tm** [comment]
Ok. Thank you jonathantneal: that's an excellent answer.

**Comment by jonathantneal** [comment]
If anyone figures out a way to improve things from 80% to 83.3~%, I’m open to that PR.
