### ISSUE TITLE
sup, sub

### ISSUE THREAD

**Issue by juytter** [csstools/sanitize.css#175]
i can't find the sub / sup rules from normalize.css

>  /**
>  * Prevent `sub` and `sup` elements from affecting the line height in
>  * all browsers.
>  */

Any reason why ?

**Comment by jonathantneal** [comment]
While I once enjoyed that fix for the perceived purity of sub and sup elements, I don’t think it’s wise to radically change the default styling of those elements. They are definitely not normalizations in the sense of polyfills, but rather opinionated defaults. I’m not presently interested in that opinionated default for sanitize.css.

**Comment by juytter** [comment]
Not "opinionated defaults". That's a common (typographic) browsers inconsistency fix. Also, normalize.css removed  "opinionated" default things over the time.

Alternatively, if we care about visual consistency (line height),  how can we  fix this by default without adding a reset(.css) to sanitize.css ?
