### ISSUE TITLE
Latest published version is 7.0.3, not 8.0

### ISSUE THREAD

**Issue by Cordazar** [csstools/sanitize.css#176]
Latest published version is 7.0.3, not 8.0.

**Comment by jonathantneal** [comment]
Hi @Cordazar, I’m not sure if you’re experiencing a caching issue, but I would look into it.

https://www.npmjs.com/package/sanitize.css

<img width="380" alt="Screenshot of npmjs.com showing sanitize.css at version 8.0.0" src="https://user-images.githubusercontent.com/188426/50349671-9dfe2080-050a-11e9-8e37-e5c4a77dd5f5.png">

**Comment by hacknug** [comment]
@Cordazar is right although it looks like it's only an issue with the displayed number and nothing else (`svg:not([fill])` is there so it really is v8.0.0 and not a different version like it would seem).

If you take a look at the file's comments on the first line you'll see what he meant:
- https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/8.0.0/sanitize.css
- https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/8.0.0/sanitize.min.css
- https://csstools.github.io/sanitize.css/latest/sanitize.css
