### ISSUE TITLE
[Firefox Bug] Remove red shadow from invalid inputs.

### ISSUE THREAD

**Issue by notiv-nt** [csstools/sanitize.css#177]
We have:

`form > input[required]`

**1.** Type something in input.
**2.** Clear input

### Chrome/Safari

![chrome](https://user-images.githubusercontent.com/10743009/50379649-3659e980-0660-11e9-8312-3ae2897c5027.gif)

### Firefox

![ff](https://user-images.githubusercontent.com/10743009/50379648-2a6e2780-0660-11e9-862a-6cf8578edf6d.gif)

### With box-shadow: none

![ch-ff](https://user-images.githubusercontent.com/10743009/50379681-0232f880-0661-11e9-931f-98187b78de8b.gif)

it is automatically added to inputs in vue `v-model` 
https://codesandbox.io/s/l5wzv7r069 

https://stackoverflow.com/questions/3809146/firefox-4-required-input-form-red-border-outline

http://jsfiddle.net/p3ozk9fu/6/

**Comment by jonathantneal** [comment]
I generally avoid form normalization beyond spacing. Is the styling a result of it being required or a result of it being invalid? Any normalizations should apply to the right scenario.

**Comment by notiv-nt** [comment]
hmm, right, its just invalid

**Comment by notiv-nt** [comment]
but it is still a solution

```
:invalid {
    box-shadow: none;
}
```

**Comment by jonathantneal** [comment]
@notiv-nt, perhaps. We’ll have to check the spec to see if an invalid state should be visually indicated to the user. If it should, then we’ll have to see why the other browsers may not be showing the same style. Once we know the real discrepancy then we may clear `box-shadow` or we may end up adding the consistent rule to all browsers. I would lean on whatever the spec says to do, unless the pattern seems wrong to a large subset of developers.

**Comment by notiv-nt** [comment]
I do not see anything about it in the spec

**Comment by notiv-nt** [comment]
![image](https://user-images.githubusercontent.com/10743009/57648447-31c1ad80-75ce-11e9-978a-ab77c7d29562.png)

https://gist.github.com/tagliala/6143525

**Comment by jonathantneal** [comment]
@notiv-nt, from my research it looks like `:invalid` is applied differently than `:-moz-ui-invalid`. Namely, `:invalid` applies on first view, while `:-moz-ui-invalid` requires user interaction to be triggered.

Therefore, unless you have strong objection, I would mark this as a normalization to be applied as:

```css
:-moz-ui-invalid {
  box-shadow: none;
}
```

https://github.com/csstools/sanitize.css/blob/87ce42cc54e9bf182bdf007e50759e01fa010d6c/sanitize.css#L400-L406

**Comment by notiv-nt** [comment]
yes, looks like it works
