### ISSUE TITLE
sanitize.css@8.0.0 on npm has v7.0.3 header

### ISSUE THREAD

**Issue by AviVahl** [csstools/sanitize.css#182]
Today I've installed `sanitize.css@8.0.0` using yarn, and noticed the header of `sanitize.css` says:
```css
/*! sanitize.css v7.0.3 | CC0 License | github.com/csstools/sanitize.css */
```

I suggest publishing v8.0.1 with a fixed header to avoid user confusion.
Thank you for your work. Appreciate the library.

**Comment by hacknug** [comment]
Duplicate of #176 (closed, not addressed).

**Comment by AviVahl** [comment]
This re-enforces my suggestion. I mean, it's not really an issue... just a source of confusion.

Anyhow, I'm closing this... feel free to publish or not.
