### ISSUE TITLE
vertical-align svg

### ISSUE THREAD

**Issue by mdkq** [csstools/sanitize.css#189]
I'm having an issue with svg icons basically identical to this: 
https://github.com/googlearchive/paper-button/issues/7#issuecomment-45935143

Would it make sense to remove/change `vertical-align: middle` for svg in sanitize?

Thanks for the great work. The library has been really useful for me.

**Comment by jonathantneal** [comment]
Thanks for reporting the issue and giving me that context. Would you mind sharing a CodePen or something with an example of the bug using sanitize.css? I’d like to investigate this a bit further before making a change.

**Comment by mdkq** [comment]
I'm sorry to leave you hanging, but I can't seem to reproduce it in an isolated environment.
