### ISSUE TITLE
Add CHANGELOG.md?

### ISSUE THREAD

**Issue by ungoldman** [csstools/sanitize.css#19]
@jonathantneal how do you feel about adding a `CHANGELOG.md` file to help keep track of changes between version bumps?

http://keepachangelog.com/ has some great reasoning around why to do so and a good format as well.

**Comment by davidhund** [comment]
:+1:
Also: I'd love to be able to see (e.g. at the top in the README) the current version.

**Comment by jonathantneal** [comment]
Resolved in 2.0.0
