### ISSUE TITLE
input[type=range] thumb is offset by padding

### ISSUE THREAD

**Issue by jasonhibbs** [csstools/sanitize.css#198]
Seen in Chrome 83 on macOS 10.15.5

When using sanitize/forms, range input thumbs are misaligned due to the padding applied to all inputs.

Setting left/right padding to 0 corrects this.

![Screenshot 2020-06-22 at 15 36 35](https://user-images.githubusercontent.com/919628/85300306-4abdb300-b49e-11ea-9d90-d1cbadfad700.png)

[View in Codepen](https://codepen.io/jasonhibbs/pen/oNbZRyB)

**Comment by jonathantneal** [comment]
This will be fixed in the next version.

**Comment by jonathantneal** [comment]
Fixed in 7739286
