### ISSUE TITLE
<pre> word-wrap and layout breaking

### ISSUE THREAD

**Issue by marcop135** [csstools/sanitize.css#199]
Hi,
I wonder why you didn't add a `white-space` or an `overflow` to the `pre` element.
You could wrap it and don't let it break the layout by default when the text is very long. 

Please see [this test case](https://codepen.io/marcop135/pen/bGEzXeo) where you can see that a long text breaks the layout horizontally.
Adding `pre { white-space: pre-wrap }` could be a fix.

Pro:
Increasing the responsiveness of the whole project

Cons:
?

Reference: 
- [How do I wrap text in a pre tag?](https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag)
- [@jensimmons CSS Remedy fix](https://github.com/jensimmons/cssremedy/blob/v0.1.0-beta.2/css/remedy.css#L85)
- [@twbs Reboot fix](https://github.com/twbs/bootstrap/blob/v4.5.0/dist/css/bootstrap-reboot.css#L157)

**Comment by jonathantneal** [comment]
Thanks for sharing this. It looks like Bootstrap’s reboot fix honors the default formatting of a `<pre>` without passing overflow to its container, and so I will follow that version.

**Comment by jonathantneal** [comment]
Added in 58990c7
