### ISSUE TITLE
Background-repeat is not in the stylesheet

### ISSUE THREAD

**Issue by Jeremy-Bolella** [csstools/sanitize.css#204]
The readme shows that there is `background-repeat: no-repeat;` but it is not in the npm modules folder in any of those css files

**Comment by katiehartrick** [comment]
[V6.0.0](https://github.com/csstools/sanitize.css/commit/4bf3a92b43d181f4738743c8ff06da77a7a89aa7) updates the readme for `background-repeat: no-repeat`, style is not added to stylesheet

**Comment by jonathantneal** [comment]
Closed in https://github.com/csstools/sanitize.css/pull/208
