### ISSUE TITLE
Height: 100% on html/body?

### ISSUE THREAD

**Issue by Flo2ent** [csstools/sanitize.css#206]
https://github.com/jensimmons/cssremedy/issues/70
My proposal: https://github.com/jensimmons/cssremedy/issues/70#issuecomment-764941135

**Comment by jonathantneal** [comment]
Thanks to logical properties and cross-browser support for the fallback properties of stretch, this has been added! 🎉 

https://github.com/csstools/sanitize.css/commit/9bbf845ad6c5f5e5471ed078c73029c2e0bce1c7

Thanks, @Flo2ent! This totally fixes a super frustrating part of design.
