### ISSUE TITLE
sanitize.css adds an extra dotted outline to focused buttons in Firefox

### ISSUE THREAD

**Issue by simevidas** [csstools/sanitize.css#209]
Steps to reproduce:

1. Open in Firefox: https://jsbin.com/zoletuk/edit?html,css,output
2. Focus the button via the keyboard

Firefox shows its native focus indicator, but sanitize.css shows a dotted outline on top of that (at the same time):

<img width="695" alt="Screen Shot 2021-03-03 at 1 04 55 AM" src="https://user-images.githubusercontent.com/716405/109732163-e9b5b580-7bbc-11eb-9fbe-69941819794b.png">

On my website, I have removed this dotted outline by applying this hotfix in my CSS code:

```css
:-moz-focusring {
  outline: revert;
}
```

I haven’t yet figured out what sanitize.css should do..

**Comment by jonathantneal** [comment]
It seems like what this fixed is no longer an issue in Firefox. It’s been removed in https://github.com/csstools/sanitize.css/commit/7cf51168ff3fcf8c94a871cd34a0e3305820f007

Thank you for the clear report, @simevidas !
