### ISSUE TITLE
list-style-type:none for <ol> ?

### ISSUE THREAD

**Issue by abhishekrawat22** [csstools/sanitize.css#215]
Why is list-style-type:none used for ol in line 96? We use ol to show lists in a numbered order and this property is removing what separates ol from ul.

**Comment by kernc** [comment]
This should only affect lists inside [`<nav>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), i.e. navigation menus.
https://github.com/csstools/sanitize.css/blob/9bbf845ad6c5f5e5471ed078c73029c2e0bce1c7/sanitize.css#L96-L97

**Comment by abhishekrawat22** [comment]
Oh! Got that. My bad.
