### ISSUE TITLE
Should set `cursor: pointer` on the `[aria-controls]` elements?

### ISSUE THREAD

**Issue by yuheiy** [csstools/sanitize.css#218]
The `[aria-controls]` elements do not necessarily have to be button-like. For example, a text field may control another element, such as a combo box.

https://www.w3.org/TR/wai-aria-practices-1.2/#combobox

And since many buttons do not have the `aria-controls` attribute, it seems unnatural that only the `[aria-controls]` element has `cursor: pointer` set.

**Comment by abhishekrawat22** [comment]
@yuheiy If any element is controlling some other element that means there is an event to occur, whether it is to display a modal or a read more part.  So ```cursor: pointer``` is needed because that element is linked to something. That's the default for any clickable thing.

**Comment by jonathantneal** [comment]
I agree. This should not be in the project. Fortunately for me, `aria-controls` [doesn’t actually work in any reliable way](https://heydonworks.com/article/aria-controls-is-poop/) and is [presently disappearing](https://twitter.com/aardrian/status/1431781878667829251).

**Comment by jonathantneal** [comment]
This has been removed in https://github.com/csstools/sanitize.css/commit/678ccd2fe3c92b47dc81537502825dce15702ed6

Thanks, @yuheiy!
