### ISSUE TITLE
Host it on a CDN

### ISSUE THREAD

**Issue by siamkreative** [csstools/sanitize.css#30]
It would be great to have this hosted on a CDN. I suggest both CDNJS and JsDeliver:
- https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
- https://github.com/jsdelivr/jsdelivr#how-to-submit-or-update-projects

We need to send PRs to both CDN repos as per their requirements...

Cheers

**Comment by thasmo** [comment]
:+1:

**Comment by jonathantneal** [comment]
@SiamKreative, it is hosted on cdnjs. https://cdnjs.com/libraries/sanitize.css

And I’ve pushed an update for the current 3.1.1 branch. https://github.com/cdnjs/cdnjs/pull/6894
