### ISSUE TITLE
directional quotes on <q> element

### ISSUE THREAD

**Issue by albell** [csstools/sanitize.css#32]
I find this handy, and just wanted to share. Others might find this a useful baseline feature:

```
q::before {content: "“"}
q::after {content: "”"}
```

http://codepen.io/anon/pen/rVpZgL

It's better for readability if readers can distinguish easily between a quote beginning or a quote ending. Thanks for sanitize-- I learned a few nice tricks I've put into use.

**Comment by tigt** [comment]
Most browsers seem to implement this already, but using the `opening-quote` and `closing-quote` keywords. That tends to work better across fonts and languages.

**Comment by albell** [comment]
Chrome/Opera/Safari default stylesheets use `open-quote`, which is currently non-directional. Look at the pen. Chrome/Opera/Safari don't accept the `opening-quote` keyword:

http://codepen.io/anon/pen/xGpmZG

So I'm not sure what you mean by "most browsers" here. Totally agreed this needs to be handled sensitively for internationalization.

**Comment by tigt** [comment]
I do see the directional quotes on my machine, which suggests this is going
to be another one of those headache incompatibility issues.

**Comment by jonathantneal** [comment]
As @Tigt says, the default works best, especially across fonts, languages (and I think text directions, too).
