### ISSUE TITLE
Does optimizeLegibility have a negative performance impact?

### ISSUE THREAD

**Issue by jmmcduffie** [csstools/sanitize.css#33]
Mat Marquis wrote [an article about `optimizeLegibility`](https://bocoup.com/weblog/text-rendering/) earlier this year that suggests it causes serious performance issues, especially on mobile devices. Does it make sense to override the browser's (apparently sensible) default for `text-rendering`?

**Comment by tigt** [comment]
From personal experience, mobile and even desktop Chrome will perform bizarre text overlapping and overflow when it's set, about 1 out of every 100 page loads. (That's what it feels like, anyway.)

It would be nice to have it on headings and such, though.

**Comment by magnus-bergman** [comment]
https://bocoup.com/weblog/text-rendering

**Comment by kexhest** [comment]
:+1:

**Comment by jonathantneal** [comment]
Agreed, and it was creating issues in Windows and Linux. This property has been removed and the updated Sanitize is [v3.1.1](https://github.com/10up/sanitize.css/tree/v3.1.1).
