### ISSUE TITLE
E-Mail Templates

### ISSUE THREAD

**Issue by thasmo** [csstools/sanitize.css#34]
Would you recommend using sanitize.css for email templates too? Thanks a lot!

**Comment by Fequois** [comment]
I'm not the author, but I would say no. A whole lot of it won't work in a vast majority of e-mail clients currently out there.

**Comment by jonathantneal** [comment]
@thasmo, you probably cannot use Sanitize, Normalize or any base library to its potential in emails. HTML emails are always built using tables and cannot use box-sizing, [as far as I know](https://www.campaignmonitor.com/css/). Also, HTML emails typically inline rules, meaning normalize and sanitize styles for pseudo elements would be lost.

I’m sorry that emails are a black box in 2016.
