### ISSUE TITLE
Bower version conflict?

### ISSUE THREAD

**Issue by robneu** [csstools/sanitize.css#38]
It looks like the latest version of this available on bower is `1.1.0`. Any way you could push the latest version up?

**Comment by thasmo** [comment]
Please! It also confuses me that there are 2 variants on bower and 3 relevant repositories. oO

http://bower.io/search/?q=sanitize-css (https://github.com/jonathantneal/sanitize.css)
http://bower.io/search/?q=sanitize.css (https://github.com/ZDroid/sanitize.css)

And of course https://github.com/10up/sanitize.css

**Comment by robneu** [comment]
While we're waiting for this to be resolved, Bower will use the GitHub repo if you add it to your `bower.json` like this:

```
"sanitize-css": "10up/sanitize.css"
```

It's just not that great for easy installation.

**Comment by thasmo** [comment]
Yep, I went with `"sanitize-css": "10up/sanitize.css#v2.0.0"`. Hopefully this will be resolved soon. :)

**Comment by jonathantneal** [comment]
this should now be resolved.

**Comment by thasmo** [comment]
I still got [problems](https://github.com/10up/sanitize.css/issues/45#issuecomment-148193152).
