### ISSUE TITLE
* { background-color:inherit; } is a major cause of pain

### ISSUE THREAD

**Issue by stereokai** [csstools/sanitize.css#43]
@jonathantneal `* { background-color: inherit; }` is a major cause of pain for us.

Especially in large projects which import components from external projects (read: enterprise scale apps and website).

For example, global components like header, footer, login forms are breaking because of that: for example, transparent elements in a global component, assume undesired background colors from their container element in an app which requires that component.

This has been a major cause of pain for us since we started using sanitize.css, because there is no way to reverse this rule - you'd have to manually add over-riding rules for each HTML element you want to fix - even though the correct background rules are already present in their respective components' stylesheets.

Please consider dropping it, because otherwise we would be forced to drop using sanitize.css, which we favor due to it being great project with a modern approach.

Thanks,
Tom Alon
Wix.com

**Comment by FabianBeiner** [comment]
Hey @stereokai, this got arleady removed last month. See https://github.com/10up/sanitize.css/commit/292c630d3607d9023b33b844b527aedfad07b70c. Please get the latest .scss and compile it for yourself, because the current .css in this repo isn't the latest version. :)

(For now, you could also use one of the files from https://github.com/FabianBeiner/sanitize.css/tree/dev/dist, which are the latest version.).

**Comment by stereokai** [comment]
Cheers. What can we do to get it into npm?

**Comment by FabianBeiner** [comment]
You'll (probably) have to wait for @jonathantneal. I'm sure he'll answer as soon as he has the time. :)

**Comment by stereokai** [comment]
Thank you very much.

**Comment by stereokai** [comment]
@jonathantneal W'sup Johnny? :+1:

**Comment by jonathantneal** [comment]
This (background-color: inherit) should not be here.

**Comment by stereokai** [comment]
I know. When are you pushing it to NPM?

**Comment by jonathantneal** [comment]
I just did.

**Comment by jonathantneal** [comment]
Resolved in 2.1x
