### ISSUE TITLE
why can not use v2.1.0 with bower?

### ISSUE THREAD

**Issue by libitte** [csstools/sanitize.css#45]
sanitize.css is published v2.1.0 for npm but not for bower.
Why is the version of the bower package supplied as the older version?
I wish the bower package is published as v2.1.0.

**Comment by jonathantneal** [comment]
I needed to update `bower.json` and that has been done. Thanks!

**Comment by libitte** [comment]
Thank you for your support https://github.com/10up/sanitize.css/commit/7b60c2e5eea459fc4250c7fa7861cfe9f7cb011c .
But, I couldn't fetch sanitize-css#2.1.1 from bower :cry: 

```
bower sanitize-css#2.1.1    not-cached git://github.com/jonathantneal/sanitize.css.git#2.1.1
bower sanitize-css#2.1.1       resolve git://github.com/jonathantneal/sanitize.css.git#2.1.1
bower sanitize-css#*            cached git://github.com/jonathantneal/sanitize.css.git#1.1.0
bower sanitize-css#*          validate 1.1.0 against git://github.com/jonathantneal/sanitize.css.git#*
bower sanitize-css#2.1.1    not-cached git://github.com/jonathantneal/sanitize.css.git#2.1.1
bower sanitize-css#2.1.1       resolve git://github.com/jonathantneal/sanitize.css.git#2.1.1
bower sanitize-css#2.1.1  ENORESTARGET No tag found that was able to satisfy 2.1.1

Additional error details:
Available versions: 1.1.0
```

**Comment by FabianBeiner** [comment]
@libitte: Looks like you're trying to get it from @jonathantneal's fork. Give https://github.com/10up/sanitize.css a try.

**Comment by libitte** [comment]
Oops. 

@FabianBeiner Thank you for you kindness.
I could fetch sanitize-css#2.1.0 from bower!

```
bower sanitize-css#2.1.0    not-cached git://github.com/10up/sanitize.css.git#2.1.0
bower sanitize-css#2.1.0       resolve git://github.com/10up/sanitize.css.git#2.1.0
bower sanitize-css#2.1.0      download https://github.com/10up/sanitize.css/archive/v2.1.0.tar.gz
bower sanitize-css#2.1.0       extract archive.tar.gz
bower sanitize-css#2.1.0      mismatch Version declared in the json (2.0.0) is different than the resolved one (2.1.0)
bower sanitize-css#2.1.0      resolved git://github.com/10up/sanitize.css.git#2.1.0
bower sanitize-css#2.1.0       install sanitize-css#2.1.0

sanitize-css#2.1.0 bower_components/sanitize-css
```

**Comment by thasmo** [comment]
@jonathantneal, I still can't install this via bower.json `"sanitize-css": "~2.1"`. It says:

``` shell
bower sanitize-css#~2.1   ENORESTARGET No tag found that was able to satisfy ~2.1
Additional error details:
Available versions: 1.1.0
```

Also searching for "sanitize" on the `bower.io` website doesn't show anything.

**Comment by thasmo** [comment]
Seems like that `sanitize-css` shows up on bower.io now, but it points to `jonathantneal/sanitize.css` which is why it can't find version 2.1.

**Comment by thasmo** [comment]
@jonathantneal, is there anything I can do to have this fixed? Thanks!

**Comment by jonathantneal** [comment]
@thasmo, I updated [bower.json](https://github.com/10up/sanitize.css/commit/ed4da2d8953de60ca429b2836efeaea9192c9b8c) earlier today, tagged the v3 release, and synced up my [old repo](https://github.com/jonathantneal/sanitize.css). Would you be able to see if this is now resolved?

**Comment by thasmo** [comment]
@jonathantneal, `sanitize-css` points to `git://github.com/jonathantneal/sanitize.css.git`. Is this intended ot should it point to `10up/sanitize.css` instead?

**Comment by jonathantneal** [comment]
Ugh, bower was a real pain. Would you please check again? Thank you in advance. Fingers crossed.

**Comment by thasmo** [comment]
It's not that bad. xD Yep, works now - thanks a lot! :)
