### ISSUE TITLE
Typography went crazy after v3

### ISSUE THREAD

**Issue by oste** [csstools/sanitize.css#52]
Just a heads up, when I installed v3 my typography went haywire. Thinking i would need to tune some things in order to get it working again. Back to normalize for now however.

**Comment by allenmoore** [comment]
Hey @oste. Can you give some additional detail for this issue? I've tested version 3 on multiple code bases and I haven't experienced any issues with typography. Thanks!

**Comment by jonathantneal** [comment]
I will be closing this if more information is not provided.

Relevant: https://github.com/jonathantneal/dear-github
