### ISSUE TITLE
`form-element-min-height` probrem

### ISSUE THREAD

**Issue by m-iskw** [csstools/sanitize.css#55]
In [sanitize.scss](https://github.com/10up/sanitize.css/blob/master/sanitize.scss) and [sanitize.styl](https://github.com/10up/sanitize.css/blob/master/sanitize.styl) `form-element-min-height` variable or function, applied `root-line-height` with '%' unit, compile to raw scss code or `min-height: ;`. Is this behavior correct?

SCSS CodePen
https://codepen.io/m-iskw/pen/wMGLqo?editors=010#0

Stylus CodePen
https://codepen.io/m-iskw/pen/GoZbQo?editors=010

**Comment by jonathantneal** [comment]
The form element’s `min-height` has been simplified to `1.5em` and released as part of [v3.1.1](https://github.com/10up/sanitize.css/tree/v3.1.1). This reduces some of the strange math needing to be introduced to each language.
