### ISSUE TITLE
text-rendering: optimizeLegibility is buggy on Windows and Linux

### ISSUE THREAD

**Issue by stereokai** [csstools/sanitize.css#58]
@jonathantneal text-rendering: optimizeLegibility is buggy on Windows and Linux:

https://github.com/Microsoft/vscode/issues/192#issuecomment-171270723

> The implementation has known bugs on Windows and Linux, which can break font substitition, small-caps, letter-spacing or cause text to overlap.

Maybe for now it'd be better to not include it by default?

**Comment by jonathantneal** [comment]
Agreed, and this is related to #33, so the property has been removed as part of [v3.1.1](https://github.com/10up/sanitize.css/tree/v3.1.1). Thanks.

**Comment by stereokai** [comment]
Cheers.
