### ISSUE TITLE
Perhaps create a test directory with HTML and PhantomCSS tests

### ISSUE THREAD

**Issue by lukewatts** [csstools/sanitize.css#59]
I know there is gh-pages, although I didn't know this until I read the previous issues about HTML tests. So test HTML could be made more prominent for people wanting to contribute or test Sanitize.css out.

Perhaps a "tests" directory with specific tests for each case would be useful.

Also, the use of [PhantomCSS](https://github.com/Huddle/PhantomCSS) for visual regression testing could be really useful when testing on updates. Could possibly even automate the entire process and simply run it from "" in the package.json.

**Comment by jonathantneal** [comment]
Yes, I would like to see a test page that can be used to toy around with what’s going on, as well as to provide a visual from previous versions.

I would like to see this in Sanitize.css and [Normalize.css](https://github.com/necolas/normalize.css). I am current looking into doing this with [BrowserStack](https://www.npmjs.com/package/browserstack). I’ll keep you posted with updates.

**Comment by lukewatts** [comment]
Yea that would work. I thought it might be handy for anyone contributing to be able to simply run something like "npm run test:phantomcss" and see the screenshots themselves. That way it's not up to you to check every pull request. But....people still probably wouldn;t bother running the tests :/

**Comment by jonathantneal** [comment]
Update: I still have not found a good solution that gives me legacy and modern browsers. Someone suggested that I put together a kickstarter for the funds to build my own browser farm for adding these tests to Sanitize and Normalize.

**Comment by lukewatts** [comment]
I'll actually be talking to someone tonight who might be able to give some ideas on a solution. I'll let you know if I come up with anything.

**Comment by lukewatts** [comment]
@jonathantneal So the more I think about it the more it depends on what the test HTML is being used for. Also thinking of Normalize.css here, there's three criteria to test for.
1. Someone removes or adds CSS which is only to improve performance and should not affect layout in anyway. This is where checking the diff on the CSS file is useless and Visual Regression testing is required to make sure "optimization-only" updates don't affect resulting styles.
2. Dropping a vendor prefix or an older browser (IE8). These changes shouldn't affect newer browsers (IE9+ and let's say). This could also apply to adding tweaks for a new browser versions quirks. Let's say a fix for new Chrome bug shouldn't mess with older Chrome versions. And even adding a new browser
3. Simply checking where the differences between browser are most drastic to determine where Sanitizing/Normalizing is required.

Does that sound about right?

**Comment by lukewatts** [comment]
Found this [CrossBrowserTesting API](https://crossbrowsertesting.com/apidocs/v3/screenshot-comparisons.html#!/default/get_screenshots_target_screenshot_test_id_target_version_id_target_result_id_comparison_base_result_id)

Maybe it'll allow for automating the whole process by integrating their API into the build/test process.

**Comment by jonathantneal** [comment]
I’ve been using CrossBrowserTesting with great success. If someone comes across script for using this locally or as part of a travis script, I will use it in both sanitize.css and normalize.css.

In the meantime, I’ll look into a test.html similar to the one in normalize.css

**Comment by lukewatts** [comment]
Awesome!

**Comment by jonathantneal** [comment]
I now have a test.html file similar to normalize.css that will be pushed with each release.
