### ISSUE TITLE
Set default tab-size to 4

### ISSUE THREAD

**Issue by jonathantneal** [csstools/sanitize.css#60]
@Alhadis [wrote](https://github.com/necolas/normalize.css/issues/461):

> the default tab-width of 8 characters used by systems and terminals really doesn't cut it for the web. When code's indented with hard tabs, they're almost always 4-characters wide, not 8. Maybe have a global stylesheet rule to set the tab-size to a sensible value?

This seems like a exactly the kind of opinionated feature meant for Sanitize.css.

**Comment by Alhadis** [comment]
Apropos of tabs, good to see this repo's using them!

**Comment by jonathantneal** [comment]
A few observations.
1. [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) is [not supported](http://caniuse.com/#feat=css3-tabsize) in Edge or Internet Explorer, and the Edge team is [not super interested](https://dev.windows.com/en-us/microsoft-edge/platform/status/csstabsizeproperty) in adding it anytime soon.
2. The default tab size in Edge and Internet Explorer is 8, so setting this property for other browsers would create an inconsistent experience in many cases where it actually mattered.
3. `*`, `::before`, and `::after` already inherit the value from `:root`.

So, the inconsistencies created by 1 and 2 make me hesitant to add this into Sanitize.css until Edge at least moves it up a notch in priority.

**Comment by Alhadis** [comment]
Microsoft holding the web back. Who woulda thought, eh?

(I left them a comment, and I'm laughing at the fact they censored "goddamn" as though it were an F-bomb...)

**Comment by jonathantneal** [comment]
Since there has been no development on `tab-size` support and the default is consistent across all browsers, I am going to close this out. Should support change, anyone is free to create a new issue.
