### ISSUE TITLE
`npm run test` in Contributing documentation

### ISSUE THREAD

**Issue by zrothauser** [csstools/sanitize.css#62]
CONTRIBUTING.md currently includes a reference to running `npm run test`, but there are no tests set up yet - this line in the Contributing file is a bit confusing.

**Comment by jonathantneal** [comment]
Thanks for spotting this, @zrothauser. I added a `.stylelintrc` file, a lint test, and this has been released as part of [v3.1.1](https://github.com/10up/sanitize.css/tree/v3.1.1)
