### ISSUE TITLE
Direct descendant selector for nav lists

### ISSUE THREAD

**Issue by ZoeBijl** [csstools/sanitize.css#69]
```
nav ol,
nav ul {
    list-style: var(--nav-list-style, none);
}
```

Not exactly sure what this code does, I'm guessing it defaults `list-style` to none (as I don't see `--nav-list-style` defined in the code). I know this is common practice, but this might not make sense of nested lists. Would something like this make more sense?

```
nav > ol,
nav > ul {
    list-style: var(--nav-list-style, none);
}
```

**Comment by lukewatts** [comment]
I assume this is mainly for a dropdown style site navigation which would require a second and third level drop down (ul) to look and behave the same as the first level ul/ol. You wouldn't want the second or third level dropdown list items to have bullets in 99% or the circumstances I would say.

**Comment by ZoeBijl** [comment]
Yeah that is fair. I was thinking mega menus.

**Comment by jonathantneal** [comment]
@MichielBijl, thanks for checking out our code today. I love the questions.

[CSS variables](https://www.w3.org/TR/css-variables/) allow a fallback. By not defining `--nav-list-style`, I’m allowing developers to override this in their own stylesheets. If you’ve worked with Sass, this is similar to [!default](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_).

As @lukewatts points out, this follows a cowpath developers have taken of removing the default styling of lists within `<nav>`. Therefore, the looser descendant selector is used over the direct decendant `>`.

Thanks again for checking out this project. :)

**Comment by ZoeBijl** [comment]
> CSS variables allow a fallback. By not defining --nav-list-style

Cool, didn't know that.

> this follows a cowpath developers have taken of removing the default styling of lists within `<nav>`

That makes sense. Another concern was lists with `list-style: none` not being announced as lists—and thus not announcing their length. After some testing it seems that is limited to Safari and VoiceOver though (tested with Safari 9 on OS X 10.10 and iOS 9.2). So I'm not sure this warrants any change (probably not).

> Thanks again for checking out this project. :)

No problem!
