### ISSUE TITLE
* { border: 0; }

### ISSUE THREAD

**Issue by oste** [csstools/sanitize.css#7]
While doing some testing with this reset I ran into some issues where descendent elements were getting undesired borders. Adding `* {
  border: 0;
}`was useful for me.

**Comment by jonathantneal** [comment]
@oste, great catch! Would you test [this new version](https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss) which includes [several updates](https://github.com/jonathantneal/sanitize.css/commit/88d43cb8357a24a29d3b9d7671742da776ba4e3d)?

I believe [what you are looking for is there](https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss#L110-L117).

**Comment by oste** [comment]
yep, looks good
