### ISSUE TITLE
Firefox button padding

### ISSUE THREAD

**Issue by mdmoreau** [csstools/sanitize.css#73]
Just ran into an issue with Firefox's default button padding and had to use something from normalize to fix it:

```
/**
 * Remove inner padding and border in Firefox 4+.
 */

button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
  padding: 0;
}
```

Is that something you'd consider adding to sanitize.css?  Really useful stuff by the way - enjoying the switch from normalize a lot so far.

**Comment by jonathantneal** [comment]
Thanks! Yes, this has been brought in as part of v3.3.0 3358dbd!

**Comment by mdmoreau** [comment]
Awesome - thanks!
