### ISSUE TITLE
CSS isn't clean

### ISSUE THREAD

**Issue by corysimmons** [csstools/sanitize.css#77]
Not properly indented:
![image](https://cloud.githubusercontent.com/assets/224636/13510807/61eda8ac-e160-11e5-9fb0-8e5db720a77d.png)

Empty rulsets:
![image](https://cloud.githubusercontent.com/assets/224636/13510821/71544df0-e160-11e5-9788-264c45c57f09.png)

Selectors not newlined:
![image](https://cloud.githubusercontent.com/assets/224636/13510833/814dac74-e160-11e5-9dae-03beda206249.png)

Comments touching:
![image](https://cloud.githubusercontent.com/assets/224636/13510843/8e82c0aa-e160-11e5-9a42-ed3bf160de94.png)

GitHub's default huge-ass tab indents (fix with .editorconfig):
![image](https://cloud.githubusercontent.com/assets/224636/13510904/e3f85a5e-e160-11e5-80b9-a9f4c3a203ea.png)

Lack of semi-colons in some places:
![image](https://cloud.githubusercontent.com/assets/224636/13510927/0664c79e-e161-11e5-8cc5-81e5f0f293dc.png)

etc. ad infinitum.

TLC please.

**Comment by jonathantneal** [comment]
While this won’t change the functionality of the compiled CSS, I understand how PostCSS is spoiling some of the styling of the original. This sounds like a job for [perfectionist](https://github.com/ben-eb/perfectionist)

**Comment by corysimmons** [comment]
Nice! :+1:

**Comment by corysimmons** [comment]
Even in some lib files there are little OCD things. Like spacing after semi-colon on comments is 1 space everywhere except for these ones:

![image](https://cloud.githubusercontent.com/assets/224636/13533683/83f1de06-e1ff-11e5-9401-f488147c04e6.png)

I can OCD PR this if you'd like. =)

**Comment by jonathantneal** [comment]
I would welcome such a PR. For the record, I think spacing should be one space after the declaration and not necessarily aligned with each other.

**Comment by filipelinhares** [comment]
@jonathantneal do you want to lint the [CSS file](https://github.com/10up/sanitize.css/blob/master/sanitize.css) generated by postcss?

**Comment by jonathantneal** [comment]
The CSS source is clean in v4.
