### ISSUE TITLE
SVG fill: currentColor?

### ISSUE THREAD

**Issue by timhettler** [csstools/sanitize.css#78]
Whoooboy, this statement messed up my project. (lines 196–198)

I don't think this is intuitive behavior at all. At the very least, it should be a variable.

**Comment by jonathantneal** [comment]
Hi @timhettler. First, sorry to hear that you had any trouble at all. Second, `svg { fill: currentColor; }` was inspired by the css-tricks article [Cascading SVG Fill Color](https://css-tricks.com/cascading-svg-fill-color/). Does this better pitch why matching the fill to the current color might be intuitive as a baseline?

Would you tell me a little more about what happened in your project? Without any idea of what you were doing, I can’t begin to understand the situation or the solution.

**Comment by timhettler** [comment]
The `fill` property cascades, so in the aforementioned project we set that property on a parent element and let it trickle down. Unfortunately `svg { fill: currentColor; }` overrides that.

Honestly, the real problem was that this change was released as a minor version, so our deploy process picked it up when it ran `npm install`. (In the world of CSS global scoping, I acknowledge that it's hard to determine what's a "major" vs. a "minor" change.)

The project hasn't been released yet, so it cause some developer confusion, but didn't cause any real damage. We'll shrink-wrap our project dependencies when we release.

For the future releases, a Changelog would be great so it's easier to identify these types of changes. (Apologies if that already exists, but i couldn't find it.)

**Comment by jonathantneal** [comment]
@timhettler, it _is_ difficult to know whether a change to CSS is major or minor. Every style has a default, therefore any change — including a new feature — may be considered incompatible.

semver discussions aside, I would like to move `fill: currentColor` to `:root` and make a new release.

Also, I keep a thorough [CHANGELOG.md](https://github.com/10up/sanitize.css/blob/master/CHANGELOG.md) for this project and also one for [normalize.css](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md).

**Comment by timhettler** [comment]
Ah, _there_ it is. Surprised that GitHub doesn't bubble that up in some way. Thanks, @jonathantneal

**Comment by jonathantneal** [comment]
While you closed this issue, I did want to follow up with you, and I hope that’s not a bother.

I was experimenting with your situation last night, and I could not get `fill` to inherit as we suspected it would. I tried something like:

``` css
* {
  fill: inherit;
}

:root {
  fill: currentColor;
}
```

with

``` html
<svg width="100" height="100" viewBox="0 0 100 100" style="color:red">
  <path d="M0,0L0,100L100,100,L100,0"/>
</svg>
```

And the `<svg>` did not `inherit` the `fill` value from `:root`. Interestingly enough, the computed value of `fill` was red, though, for both the `<svg>` and the `<path>`.

So, for the time being, it seems like `svg { fill: currentColor }` is the most sane approach.

**Comment by timhettler** [comment]
Happy to follow up. Here's the basic implementation I'm using in our project: http://codepen.io/anon/pen/BKzjmg

I prefer to use `fill` because it's clearer that the intention is for a child SVG to be styled. However, I can see how many would find it convenient for an SVG element to inherit the `currentColor` as the fill, unless specifically overridden.

I do agree that `svg { fill: currentColor }` is the best way to accomplish what you're setting out to do.
