### ISSUE TITLE
Pure CSS version contains `&` selectors?

### ISSUE THREAD

**Issue by lo48576** [csstools/sanitize.css#79]
I want to use pure CSS version with CSS variables, but `/lib/sanitize.css` contains `&` selectors (for example, [here](https://github.com/10up/sanitize.css/blob/0e5273d8db81e840cbeac1454ad238c39b192395/lib/sanitize.css#L30)), and `/sanitize.css` doesn't use CSS variables.

Is this mistake, or does it require to be compiled?
If I should compile them, how to?
(Compiling with `scss` after renaming `lib/sanitize.css` -> `sanitize.scss` seems to produce expected pure CSS, but I don't think it is the correct way...)

**Comment by Fequois** [comment]
@l1048576 Possibly a build mistake? The project root has a [pure CSS](https://github.com/10up/sanitize.css/blob/master/sanitize.css) version.

**Comment by jonathantneal** [comment]
@l1048576, @Fequois, the `lib/sanitize.css` file uses modern CSS that may not be available to all browsers. It is transpiled down to the more-compatible `sanitize.css` file. You can learn more about it at http://cssnext.io/.
