### ISSUE TITLE
Vertical align media elements?

### ISSUE THREAD

**Issue by davidhund** [csstools/sanitize.css#8]
Have you considered the following?

```
/*
 * Remove the gap between images, videos, audio and canvas and the bottom of
 * their containers: h5bp.com/i/440
 */
audio,
canvas,
img,
svg,
video {
    vertical-align: middle;
}
```

**Comment by jonathantneal** [comment]
Yes, and I am still considering it, albeit not focused on it. The current vertical-align is set to `top` universally, which is very clean and has worked for me for a long time. More research is needed.

A few references:
https://github.com/h5bp/html5-boilerplate/issues/440
https://github.com/necolas/normalize.css/pull/54
https://github.com/necolas/normalize.css/issues/426

**Comment by jonathantneal** [comment]
Committed: https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss#L154-L163

**Comment by davidhund** [comment]
Cool, thanks for your work!
