### ISSUE TITLE
Remove -ms-overflow-style: -ms-autohiding-scrollbar; ?

### ISSUE THREAD

**Issue by perceptbe** [csstools/sanitize.css#88]
`-ms-overflow-style: -ms-autohiding-scrollbar;`

Does something like this need to be in sanitize.css? This actually makes scrollbars run over my content which no other browser does AFAIK and just makes stuff look mis-aligned on the right side of the page.

**Comment by nicolasparada** [comment]
I like autohiding scrollbar, but it's true that no other browser does that, so it makes sense to not to be on sanitize.css...

**Comment by jonathantneal** [comment]
Agreed. This will be removed in the next major release.

**Comment by thasmo** [comment]
Will it bre removed only or set to a [useful default](https://msdn.microsoft.com/en-us/library/windows/apps/hh441298.aspx), e.g. `scrollbar`?

**Comment by jonathantneal** [comment]
Done and released in v4
