### ISSUE TITLE
border-style: solid on everything?

### ISSUE THREAD

**Issue by perceptbe** [csstools/sanitize.css#89]
`*,
:before,
:after {
    border-style: solid;
    border-width: 0;
}`

is this really needed? I don't see what this is supposed to fix?

It causes google map arrows to be positioned wrong.

**Comment by AntonTrollback** [comment]
It's not needed. Universal stuff like this (everything besides box-sizing) are in my opinion just added confusion caused by coders being lazy.
Better suited for autocomplete in your editor - if these things are annoying to type/remember.

**Comment by jonathantneal** [comment]
No more `border-style: solid`. I thought it was very useful, but it introduced too many bugs. See https://github.com/10up/sanitize.css/issues/90
