### ISSUE TITLE
sanitize.css v4 plan

### ISSUE THREAD

**Issue by jonathantneal** [csstools/sanitize.css#90]
Good news! I’ll have some time to resolve the remaining sanitize.css issues and release v4. Here are the major changes I’m planning. I’d love your feedback.
### Normalize
- Everything (not reset) from normalize.css v4.
### Being kept
- Remove margin and padding (`margin: 0; padding: 0`).
- Remove tapping delay (`touch-action: manipulation`).
- Remove the text decoration on links.
- Remove the list style within navigation sections.
- Fills default to the text color (`fill: currentColor`).
- Limit the resize to vertical on text areas.
- Remove repeated backgrounds by default `background-repeat: no-repeat`.
- Specify default text selection styles.
- Specify default form styles.
### Being removed
- Don’t reset borders `border-style: solid; border-width: 0;`. While I really enjoy _not_ worrying about `border-style`. Unfortunately, like `overflow: hidden`, it comes with unexpected consequences that make it not worth the benefits.
- Autohiding scrollbars (`-ms-overflow-style: -ms-autohiding-scrollbar;`).
### Being considered
- Be border box aggressive (`* { box-sizing: border-box; }`).
- Inherit all font properties (`* { font: inherit; }`).
- Move page background to `body` (from `:root`).
- Default flex to columns (`flex-flow: column`).
- Default flex shink to `0` (`flex-shrink: 0;`).
### Not being considered
- Inherited display (`display: inherit`).
- Hidden overflow (`overflow: hidden`) because it creates unexpected consequences.
- Relative position (`position: relative`) because it creates unexpected consequences.

**Comment by luixxiul** [comment]
> Default flex to columns (flex-flow: column).

I don't understand why this would be necessary. Is there any problem out there?

**Comment by filipelinhares** [comment]
I was having some problems so a I made a project called [sanilize.css](http://filipelinhares.github.io/sanilize.css). It is a combination of sanitize and Normalize. It also removes some unexpected rules from sanitize.css like `border-style: solid; border-width: 0`. 

Happy to hear sanitize.css is moving on :smile:

**Comment by marcustisater** [comment]
Sweet, I agree with the list you've made, not really much to add or argue about. However I do think setting default flex values should be considered even if I I do dislike the standard value we have today for flex.

**Comment by jonathantneal** [comment]
Thanks for the feedback. At this time, it seems wisest to really cut down on the resets and focus on the defaults people really want and rarely redefine themselves on any element. Things like `flex-flow` will be cut. FWIW, it was a default passed around Twitter and incorporated in [css-layout](https://github.com/facebook/css-layout#default-values). Check out that project to see their _defaults_. Let me know what you think.

I plan on sanitize.css v4 being a kind of normalize.css with `border-box` and sprinkled `inherit` to make things behave similarly, and (I think) more sanely. Again, these defaults are for things you wouldn’t intend to overwrite later. This brings `margin` into question, actually. As much as zeroing out margin is great for _most_ navigations, it’s not great when you’re writing `p` and `ul` tags in your content.

I really want this to be a library that helps people build a better web based on develop preferences, but never accidentally _throwing the baby out with the bathwater_, as they say.

**Comment by marcustisater** [comment]
I will definitely have a closer look into this, will report with more detailed feedback.

**Comment by jonathantneal** [comment]
v4 is released!
