### ISSUE TITLE
Unintended Sass division in root font

### ISSUE THREAD

**Issue by dlwalsh** [csstools/sanitize.css#93]
The following line in sanitize.scss:

```
font: if(variable-exists(root-font-size), $root-font-size, 100%)/#{if(variable-exists(root-line-height), $root-line-height, 1.5)} if(variable-exists(root-font-family), $root-font-family, sans-serif);
```

is being compiled to:

```
font: 66.66667% sans-serif
```

instead of:

```
font: 100%/1.5 sans-serif;
```

This only occurs after upgrading node-sass from 3.4.2 to 3.5.1. I don't know whether this is an intentional change in the compiler or a regression in LibSass 3.3.5.

**Comment by jonathantneal** [comment]
Thanks @ciju !

**Comment by thasmo** [comment]
Will there be a patch-release soon which incorporates this fix?

**Comment by simon-lifelike** [comment]
@ciju could you cut a patch release with this fix included? thanks
