### ISSUE TITLE
Release 3.3.1

### ISSUE THREAD

**Issue by simon-lifelike** [csstools/sanitize.css#97]
With the fix in #95, as the sass/scss version is currently (somewhat) broken in 3.3.0.

**Comment by jonathantneal** [comment]
This would need to be a strange release for 3x, as the master branch of sanitize.css has moved far into a 4x release. Unfortunately, Sass broke midway. I’m working on the 4x release, but the internet is very weak here in the [hospital](https://twitter.com/jon_neal/status/728159901177008128).

**Comment by simon-lifelike** [comment]
Hey, congrats man! 

However, making a patch release with this change shouldn't be too complex, even with the master being ahead (doesn't seem like it is on the remote though? Unless I'm overlooking something).

I just tried this in a fork and it worked fine:

``` sh
$ git checkout tags/v3.3.0
$ git cherry-pick 998ea92
$ npm version patch
$ git push --tags
```

\+ `npm publish` etc

Result: https://github.com/simon-lifelike/sanitize.css/tree/v3.3.1

In any case, it's not a huuuge deal since we can still override the font definition manually. But it would be nice to have the stable version working again :)

Thanks for a great project! And best of luck

**Comment by jonathantneal** [comment]
Version 4 is released!

**Comment by vinkla** [comment]
@jonathantneal no more SASS/SCSS support in version 4.0?
