### ISSUE TITLE
Update Bower and NPM Versions

### ISSUE THREAD

**Issue by allenmoore** [csstools/sanitize.css#99]
The versions of Sanitize.css available from both Bower and NPM does not reflect the most recent changed on Github. While the version numbers match, the changes made to this line in particular does not reflect master on Github -- https://github.com/10up/sanitize.css/blob/master/lib/sanitize.scss#L249.

**Comment by simonkberg** [comment]
Fwiw the master branch shouldn't always match the current release. For the release of that particular fix see #97

**Comment by jonathantneal** [comment]
These have been updated.
